In [9]:
def undup(l):
    res = []
    for item in l:
        if item not in res:
            res.append(item)
    return res

l = input()
print(undup(l))

[1,2,3,3,4,1,5,5,5]
['[', '1', ',', '2', '3', '4', '5', ']']


In [12]:
def numres(nl):
    sum = 0
    for n in nl:
        sum = sum + n
    mean = sum/len(nl)
    return []

testlist = input()
print(numres(testlist))


1 2 3


TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [14]:
xlist = [l,['a','b',['x', 'y']]]

In [16]:
xlist = [l,['a','b',['x', 'y']]]

# Accessing 'y' using indexing
letter_y = xlist[1][2][1]

# Printing the letter 'y'
print(letter_y)
print(xlist)

y
['[1,2,3,3,4,1,5,5,5]', ['a', 'b', ['x', 'y']]]


In [18]:
import random
x = random.randint(0,100)
print(x)

42


In [21]:
randlist = []
for i in range(20):
    randlist.append(random.randint(0,100))
    
print(randlist)

[25, 61, 72, 96, 60, 36, 20, 70, 27, 97, 59, 51, 90, 45, 40, 95, 3, 0, 46, 65]


In [22]:
randlist.sort()
print(randlist)

[0, 3, 20, 25, 27, 36, 40, 45, 46, 51, 59, 60, 61, 65, 70, 72, 90, 95, 96, 97]


In [23]:
sorted_list = randlist.sort()
print(sorted_list)

None


sort method doesn't return anything so it is void

In [24]:
bigger = randlist.append(150)
print(bigger)
print(randlist)

None
[0, 3, 20, 25, 27, 36, 40, 45, 46, 51, 59, 60, 61, 65, 70, 72, 90, 95, 96, 97, 150]


In [26]:
def how_many_a_in_li(a,li):
    count = 0
    for item in li:
        if a == item:
            count = count + 1
            
    return count

In [30]:
list_tuple = []

for i in range(10):
    list_tuple.append((i+1, (i+1)**2))

print(list_tuple)

[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100)]


In [32]:
the_list = [(i+1, (i+1)**2) for i in range(10)]
print(the_list)

[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100)]


In [36]:
lol = [[1,2,3],[4,5,6],7,[8,9,10,11]]

lot = []
for li in lol:
    lot.append((li[0], li[-1]))
    
print(lot)

TypeError: 'int' object is not subscriptable

In [37]:
lot = []

In [38]:
s = "Mary had a litle lamb"
s_split = s.split()
print(s_split)

['Mary', 'had', 'a', 'litle', 'lamb']


In [40]:
s_joint = "*".join(s_split)
print(s_joint)

Mary*had*a*litle*lamb


In [41]:
s_replace = s.replace(' ',"*")
print(s_joint)

Mary*had*a*litle*lamb


Numpy Arrays

In [42]:
import numpy as np

In [43]:
array_1 = np.array([1,2,3])
array_1

array([1, 2, 3])

In [44]:
print(array_1)

[1 2 3]


In [45]:
x = [1 2 3]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1146416570.py, line 1)

In [47]:
my_array1 = np.array([3,6,9])
my_array1

array([3, 6, 9])

In [48]:
print(my_array1)

[3 6 9]


In [49]:
x = [3,6,9]
print(x)

[3, 6, 9]


In [50]:
p1 = array_1
print(p1)
print(type(p1))

[1 2 3]
<class 'numpy.ndarray'>


In [51]:
p1 = array_1[1]
print(p1)
print(type(p1))

2
<class 'numpy.int32'>


In [52]:
p1 = array_1[:2]
print(p1)
print(type(p1))

[1 2]
<class 'numpy.ndarray'>


In [53]:
array_2 = np.array([1,1,2])
array_3 = array_1 + array_2
print(array_3)

[2 3 5]


Elementwise Operation

In [54]:
x = [2 3 5]
print(x)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3865231715.py, line 1)

In [55]:
array_4 = np.concatenate([array_1,array_2])
print(array_4)

[1 2 3 1 1 2]


In [58]:
array_5 = np.array([[1,2,3],[4,5,6]])
print(array_5)

[[1 2 3]
 [4 5 6]]


In [59]:
array_5[1,2]

6

In [60]:
print(array_5.ndim)

2
