Numpy Arrays

Begin by importing numpy with the alias np

In [1]:
import numpy as np

A numpy array is very similar to a list.

You usually create a numpy array by making a list and using the function np.array()

In [2]:
array_1 = np.array([1,2,3])
array_1

array([1, 2, 3])

Display Format
Printing an array shows a list-like structure but without commas. However, you can't use this to create an array.

In [3]:
print(array_1)

[1 2 3]


In [4]:
x = [1 2 3]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1146416570.py, line 1)

Selecting parts of an array.
This works the same way as with lists.

In [5]:
p1 = array_1[1]
print(p1)
print(type(p1))

2
<class 'numpy.int32'>


In [6]:
p2 = array_1[:2]
print(p2)
print(type(p2))

[1 2]
<class 'numpy.ndarray'>


Elementwise Operation

In [7]:
array_2 = np.array([1,1,2])
array_3 = array_1 + array_2
print(array_3)

[2 3 5]


Concatenation
Use the concatenate function

In [8]:
array_4 = np.concatenate([array_1,array_2])
print(array_4)

[1 2 3 1 1 2]


Multidimensional Arrays

In [9]:
array_5 = np.array([[1,2,3],[4,5,6]])

In [10]:
print(array_5)

[[1 2 3]
 [4 5 6]]


In [11]:
array_5[1,2]

6

In [12]:
print(array_5.shape)

(2, 3)


In [13]:
print(array_5.ndim)

2
