Numpy Arrays

In [1]:
import numpy as np

In [2]:
array_1 = np.array([1,2,3])
array_1

array([1, 2, 3])

In [3]:
print(array_1)

[1 2 3]


In [4]:
x = [1 2 3]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1146416570.py, line 1)

In [5]:
p1 = array_1[1]
print(p1)
print(type(p1))

2
<class 'numpy.int32'>


In [6]:
p2 = array_1[:2]
print(p2)
print(type(p2))

[1 2]
<class 'numpy.ndarray'>


In [7]:
array_2 = np.array([1,1,2])
array_3 = array_1 + array_2
print(array_3)

[2 3 5]


In [9]:
arrays_2 = [10,11,12]
arrays_3 = arrays_2 + arrays_2
print(arrays_3)

[10, 11, 12, 10, 11, 12]


In [11]:
arrays_2 = [10,11,12]
arrays_3 = arrays_2 + arrays_2
print(arrays_3+1)

TypeError: can only concatenate list (not "int") to list